version: '3'
services:
  postgres:
    build: .
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/home/postgres/test_db

volumes:
  postgres_data: 