version: '3'
services:
  target:
    build:
      dockerfile: Dockerfile
      target: target
      context: .
    ports:
    - "127.0.0.1:5432:5432"
    networks:
      pg_net:
        ipv4_address: 192.168.233.2
  my-server:
    build:
      dockerfile: Dockerfile
      target: pg10-controlled
      context: .
    ports:
    - "127.0.0.1:5433:5433"
    networks:
      pg_net:
        ipv4_address: 192.168.233.3

networks:
  pg_net:
    driver: bridge
    ipam:
      driver: default
      config:
       - subnet: 192.168.233.0/24